### ISSUE TITLE
Handle the error to overcome github/dns fluctuations

### ISSUE THREAD

**Issue by sgriffith3** [alta3/ssh-githugger#1] opened 2020-06-02 15:31 UTC
https://github.com/alta3/ssh-githugger/blob/a224c2cd8d08f360f4f800672b4e0ea042f8703a/lib/authorized_key.py#L38

The connection did not return the expected data and threw an error. Please handle this error more gracefully.

**Comment by sfeeser** [comment] 2021-03-22 00:45
@sgriffith3, is this a duplicate of #1?
I have number 1 addressed and I can replicate this problem as the program now gracefully fails when given bad data.

**Comment by sfeeser** [comment] 2021-03-25 16:19
Duplicate of  the rate limit issue #2

**Closed as completed by sfeeser** 2021-03-25 16:19 UTC
Labels: Priority: High, Status: Review Needed, Type: Bug
